enum ACTION_VARIANTS {
  FETCH_USER = "FETCH_USER",
  ADD_USER = "ADD_USER",
  FETCH_USER_ERROR = "FETCH_USER_ERROR",
  FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
  FETCH_USER_LOADING = "FETCH_USER_LOADING",

  INCREMENT_COUNT = "INCREMENT_COUNT",
  DECREMENT_COUNT = "DECREMENT_COUNT"
}

export { ACTION_VARIANTS };
